Importamos los modulos necesarios, pandas para trabajar  y numpy para trabajar nuestros datos, train test para elegir datos de entrenamiento y prueba, logisticRegression para realizar el modelo ya que es binario elejimos este modelo, y las metricas para revisar nuestra prediccion 

In [215]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

Cagamos nuestros datos con pandas dataframe

In [216]:
df=pd.read_csv('E-Commerce_train.csv',sep=';')

Obervamos el resltado del Dataframe

In [217]:
df

ID Warehouse_block Mode_of_Shipment  Customer_care_calls  \
0        1               D           Flight                    4   
1        2               F           Flight                    4   
2        3               A           Flight                    2   
3        4               B           Flight                    3   
4        5               C           Flight                    2   
...    ...             ...              ...                  ...   
8994  8995               D             Ship                    3   
8995  8996               F             Ship                    5   
8996  8997               A             Ship                    4   
8997  8998               B             Ship                    4   
8998  8999               C             Ship                    5   

      Customer_rating  Cost_of_the_Product  Prior_purchases  \
0                   2                  177                3   
1                   5                  216                2   
2                   2                  183                4   
3                   3                  176                4   
4                   2                  184                3   
...               ...                  ...              ...   
8994                1                  217                3   
8995                3                  232                3   
8996                5                  260                3   
8997                2                  184                3   
8998                4                  145                4   

     Product_importance Gender  Discount_offered  Weight_in_gms  \
0                   low      F                44           1233   
1                   low      M                59           3088   
2                   low      M                48           3374   
3                medium      M                10           1177   
4                medium      F                46           2484   
...                 ...    ...               ...            ...   
8994                low      F                 1           4177   
8995             medium      M                 3           4526   
8996             medium      F                 6           4221   
8997             medium      F                 5           5931   
8998                low      M                 4           4790   

      Reached.on.Time_Y.N  
0                       1  
1                       1  
2                       1  
3                       1  
4                       1  
...                   ...  
8994                    1  
8995                    0  
8996                    0  
8997                    1  
8998                    0  

[8999 rows x 12 columns]

In [218]:
df = df.drop(columns = ['ID'])

In [219]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='if_binary', sparse = False) # Instanciamos el encoder por binary feature

ohe.fit(df[['Gender']]) # 

df['Gender'] = ohe.transform(df[['Gender']]) # Encodeamos Street

df.head()

Warehouse_block Mode_of_Shipment  Customer_care_calls  Customer_rating  \
0               D           Flight                    4                2   
1               F           Flight                    4                5   
2               A           Flight                    2                2   
3               B           Flight                    3                3   
4               C           Flight                    2                2   

   Cost_of_the_Product  Prior_purchases Product_importance  Gender  \
0                  177                3                low     0.0   
1                  216                2                low     1.0   
2                  183                4                low     1.0   
3                  176                4             medium     1.0   
4                  184                3             medium     0.0   

   Discount_offered  Weight_in_gms  Reached.on.Time_Y.N  
0                44           1233                    1  
1                59           3088                    1  
2                48           3374                    1  
3                10           1177                    1  
4                46           2484                    1

In [220]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8999 entries, 0 to 8998
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Warehouse_block      8999 non-null   object 
 1   Mode_of_Shipment     8999 non-null   object 
 2   Customer_care_calls  8999 non-null   int64  
 3   Customer_rating      8999 non-null   int64  
 4   Cost_of_the_Product  8999 non-null   int64  
 5   Prior_purchases      8999 non-null   int64  
 6   Product_importance   8999 non-null   object 
 7   Gender               8999 non-null   float64
 8   Discount_offered     8999 non-null   int64  
 9   Weight_in_gms        8999 non-null   int64  
 10  Reached.on.Time_Y.N  8999 non-null   int64  
dtypes: float64(1), int64(7), object(3)
memory usage: 773.5+ KB


In [221]:
# One-hot encoding a single column
from sklearn.preprocessing import OneHotEncoder
from seaborn import load_dataset

ohe = OneHotEncoder()
transformed = ohe.fit_transform(df[['Warehouse_block']])
print(transformed.toarray())
df[ohe.categories_[0]] = transformed.toarray()


ohe = OneHotEncoder()
transformed = ohe.fit_transform(df[['Mode_of_Shipment']])
print(transformed.toarray())
df[ohe.categories_[0]] = transformed.toarray()


ohe = OneHotEncoder()
transformed = ohe.fit_transform(df[['Product_importance']])
print(transformed.toarray())
df[ohe.categories_[0]] = transformed.toarray()


[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 ...
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 ...
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 ...
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]]


Revisamos valores flatantes del dataframe

In [222]:
df

Warehouse_block Mode_of_Shipment  Customer_care_calls  Customer_rating  \
0                  D           Flight                    4                2   
1                  F           Flight                    4                5   
2                  A           Flight                    2                2   
3                  B           Flight                    3                3   
4                  C           Flight                    2                2   
...              ...              ...                  ...              ...   
8994               D             Ship                    3                1   
8995               F             Ship                    5                3   
8996               A             Ship                    4                5   
8997               B             Ship                    4                2   
8998               C             Ship                    5                4   

      Cost_of_the_Product  Prior_purchases Product_importance  Gender  \
0                     177                3                low     0.0   
1                     216                2                low     1.0   
2                     183                4                low     1.0   
3                     176                4             medium     1.0   
4                     184                3             medium     0.0   
...                   ...              ...                ...     ...   
8994                  217                3                low     0.0   
8995                  232                3             medium     1.0   
8996                  260                3             medium     0.0   
8997                  184                3             medium     0.0   
8998                  145                4                low     1.0   

      Discount_offered  Weight_in_gms  ...    B    C    D    F  Flight  Road  \
0                   44           1233  ...  0.0  0.0  1.0  0.0     1.0   0.0   
1                   59           3088  ...  0.0  0.0  0.0  1.0     1.0   0.0   
2                   48           3374  ...  0.0  0.0  0.0  0.0     1.0   0.0   
3                   10           1177  ...  1.0  0.0  0.0  0.0     1.0   0.0   
4                   46           2484  ...  0.0  1.0  0.0  0.0     1.0   0.0   
...                ...            ...  ...  ...  ...  ...  ...     ...   ...   
8994                 1           4177  ...  0.0  0.0  1.0  0.0     0.0   0.0   
8995                 3           4526  ...  0.0  0.0  0.0  1.0     0.0   0.0   
8996                 6           4221  ...  0.0  0.0  0.0  0.0     0.0   0.0   
8997                 5           5931  ...  1.0  0.0  0.0  0.0     0.0   0.0   
8998                 4           4790  ...  0.0  1.0  0.0  0.0     0.0   0.0   

      Ship  high  low  medium  
0      0.0   0.0  1.0     0.0  
1      0.0   0.0  1.0     0.0  
2      0.0   0.0  1.0     0.0  
3      0.0   0.0  0.0     1.0  
4      0.0   0.0  0.0     1.0  
...    ...   ...  ...     ...  
8994   1.0   0.0  1.0     0.0  
8995   1.0   0.0  0.0     1.0  
8996   1.0   0.0  0.0     1.0  
8997   1.0   0.0  0.0     1.0  
8998   1.0   0.0  1.0     0.0  

[8999 rows x 22 columns]

In [223]:
df.isnull().sum()

Warehouse_block        0
Mode_of_Shipment       0
Customer_care_calls    0
Customer_rating        0
Cost_of_the_Product    0
Prior_purchases        0
Product_importance     0
Gender                 0
Discount_offered       0
Weight_in_gms          0
Reached.on.Time_Y.N    0
A                      0
B                      0
C                      0
D                      0
F                      0
Flight                 0
Road                   0
Ship                   0
high                   0
low                    0
medium                 0
dtype: int64

In [224]:
df.describe()

Customer_care_calls  Customer_rating  Cost_of_the_Product  \
count          8999.000000      8999.000000          8999.000000   
mean              4.015113         2.994999           208.561507   
std               1.138934         1.413143            48.289172   
min               2.000000         1.000000            96.000000   
25%               3.000000         2.000000           168.000000   
50%               4.000000         3.000000           211.000000   
75%               5.000000         4.000000           249.500000   
max               7.000000         5.000000           310.000000   

       Prior_purchases       Gender  Discount_offered  Weight_in_gms  \
count      8999.000000  8999.000000       8999.000000    8999.000000   
mean          3.511501     0.495499         15.097678    3584.364596   
std           1.532074     0.500008         17.400040    1614.750194   
min           2.000000     0.000000          1.000000    1001.000000   
25%           3.000000     0.000000          4.000000    1857.000000   
50%           3.000000     0.000000          8.000000    4046.000000   
75%           4.000000     1.000000         19.000000    4999.500000   
max          10.000000     1.000000         65.000000    7846.000000   

       Reached.on.Time_Y.N            A            B            C  \
count          8999.000000  8999.000000  8999.000000  8999.000000   
mean              0.635515     0.166685     0.166685     0.166685   
std               0.481312     0.372715     0.372715     0.372715   
min               0.000000     0.000000     0.000000     0.000000   
25%               0.000000     0.000000     0.000000     0.000000   
50%               1.000000     0.000000     0.000000     0.000000   
75%               1.000000     0.000000     0.000000     0.000000   
max               1.000000     1.000000     1.000000     1.000000   

                 D            F       Flight         Road         Ship  \
count  8999.000000  8999.000000  8999.000000  8999.000000  8999.000000   
mean      0.166685     0.333259     0.160796     0.158907     0.680298   
std       0.372715     0.471405     0.367363     0.365609     0.466387   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     1.000000   
75%       0.000000     1.000000     0.000000     0.000000     1.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              high          low       medium  
count  8999.000000  8999.000000  8999.000000  
mean      0.092566     0.478720     0.428714  
std       0.289839     0.499575     0.494920  
min       0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000  
75%       0.000000     1.000000     1.000000  
max       1.000000     1.000000     1.000000

Revisamos la distribucion de la variable ojetivo

In [225]:
df['Reached.on.Time_Y.N'].value_counts()

1    5719
0    3280
Name: Reached.on.Time_Y.N, dtype: int64

In [226]:
df.tail()

Warehouse_block Mode_of_Shipment  Customer_care_calls  Customer_rating  \
8994               D             Ship                    3                1   
8995               F             Ship                    5                3   
8996               A             Ship                    4                5   
8997               B             Ship                    4                2   
8998               C             Ship                    5                4   

      Cost_of_the_Product  Prior_purchases Product_importance  Gender  \
8994                  217                3                low     0.0   
8995                  232                3             medium     1.0   
8996                  260                3             medium     0.0   
8997                  184                3             medium     0.0   
8998                  145                4                low     1.0   

      Discount_offered  Weight_in_gms  ...    B    C    D    F  Flight  Road  \
8994                 1           4177  ...  0.0  0.0  1.0  0.0     0.0   0.0   
8995                 3           4526  ...  0.0  0.0  0.0  1.0     0.0   0.0   
8996                 6           4221  ...  0.0  0.0  0.0  0.0     0.0   0.0   
8997                 5           5931  ...  1.0  0.0  0.0  0.0     0.0   0.0   
8998                 4           4790  ...  0.0  1.0  0.0  0.0     0.0   0.0   

      Ship  high  low  medium  
8994   1.0   0.0  1.0     0.0  
8995   1.0   0.0  0.0     1.0  
8996   1.0   0.0  0.0     1.0  
8997   1.0   0.0  0.0     1.0  
8998   1.0   0.0  1.0     0.0  

[5 rows x 22 columns]

In [227]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8999 entries, 0 to 8998
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Warehouse_block      8999 non-null   object 
 1   Mode_of_Shipment     8999 non-null   object 
 2   Customer_care_calls  8999 non-null   int64  
 3   Customer_rating      8999 non-null   int64  
 4   Cost_of_the_Product  8999 non-null   int64  
 5   Prior_purchases      8999 non-null   int64  
 6   Product_importance   8999 non-null   object 
 7   Gender               8999 non-null   float64
 8   Discount_offered     8999 non-null   int64  
 9   Weight_in_gms        8999 non-null   int64  
 10  Reached.on.Time_Y.N  8999 non-null   int64  
 11  A                    8999 non-null   float64
 12  B                    8999 non-null   float64
 13  C                    8999 non-null   float64
 14  D                    8999 non-null   float64
 15  F                    8999 non-null   f

In [228]:

X=df.drop(columns=['Reached.on.Time_Y.N','Mode_of_Shipment','Product_importance','Warehouse_block'], axis=1)
Y=df['Reached.on.Time_Y.N']

In [229]:
X.shape

(8999, 18)

Seleccionamos nuestros datos de entrenamiento y de test y los dividimos de manera aeatoria

In [230]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.1, stratify=Y,random_state=2)



In [231]:
X.shape, X_train.shape, X_test.shape, 

((8999, 18), (8099, 18), (900, 18))

In [232]:
modelo1=LogisticRegression()
modelo2=LogisticRegression(fit_intercept=True, penalty='l2', tol=1e-5, C=0.8, solver='lbfgs', max_iter=75,
                       warm_start=True)

In [233]:
modelo2.fit(X_train,Y_train)

LogisticRegression(C=0.8, max_iter=75, tol=1e-05, warm_start=True)

In [234]:
X_train_prediction=modelo2.predict(X_train)
Precision_Datos_entrenamiento=accuracy_score(X_train_prediction,Y_train)
from sklearn.metrics import recall_score
Calculo_Recallo=recall_score(X_train_prediction,Y_train)

In [235]:
Precision_Datos_entrenamiento,Calculo_Recallo

(0.6627978762810224, 0.7332947083816145)

In [236]:
X_test_prediction=modelo2.predict(X_test)
Precision_Datos_test=accuracy_score(X_test_prediction,Y_test)
Calculo_Recallo=recall_score(X_test_prediction,Y_test)

In [237]:
Precision_Datos_entrenamiento,Calculo_Recallo

(0.6627978762810224, 0.7348754448398577)

In [238]:
dftest=pd.read_csv('E-Commerce_test.csv',sep=';')

In [239]:
dftest = dftest.drop(columns = ['ID'])

In [240]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='if_binary', sparse = False) # Instanciamos el encoder por binary feature

ohe.fit(dftest[['Gender']]) # 

dftest['Gender'] = ohe.transform(dftest[['Gender']]) # Encodeamos Street

dftest.head()

Warehouse_block Mode_of_Shipment  Customer_care_calls  Customer_rating  \
0               F             Ship                    5                1   
1               D             Ship                    5                3   
2               F             Ship                    3                3   
3               A             Ship                    5                1   
4               B             Ship                    4                2   

   Cost_of_the_Product  Prior_purchases Product_importance  Gender  \
0                  189                2             medium     1.0   
1                  150                2               high     0.0   
2                  200                3                low     1.0   
3                  133                2             medium     1.0   
4                  260                3                low     1.0   

   Discount_offered  Weight_in_gms  
0                10           5248  
1                 9           4446  
2                 3           5739  
3                 1           4643  
4                 4           5504

In [241]:
# One-hot encoding a single column
from sklearn.preprocessing import OneHotEncoder
from seaborn import load_dataset

ohe = OneHotEncoder()
transformed = ohe.fit_transform(dftest[['Warehouse_block']])
print(transformed.toarray())
dftest[ohe.categories_[0]] = transformed.toarray()


ohe = OneHotEncoder()
transformed = ohe.fit_transform(dftest[['Mode_of_Shipment']])
print(transformed.toarray())
dftest[ohe.categories_[0]] = transformed.toarray()


ohe = OneHotEncoder()
transformed = ohe.fit_transform(dftest[['Product_importance']])
print(transformed.toarray())
dftest[ohe.categories_[0]] = transformed.toarray()


[[0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 ...
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]]
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 ...
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 ...
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [242]:
X1=dftest.drop(columns=['Mode_of_Shipment','Product_importance','Warehouse_block'], axis=1)


In [243]:
X1.shape

(2000, 18)

In [244]:
X1prediction=modelo2.predict(X1)

In [245]:
X1prediction

array([1, 1, 0, ..., 1, 1, 1], dtype=int64)

In [246]:
type(X1prediction)

numpy.ndarray

In [247]:
datasalida = pd.DataFrame(X1prediction)

In [248]:
datasalida[0].value_counts()

1    1089
0     911
Name: 0, dtype: int64

In [249]:
datasalida.columns=['pred']

In [251]:
datasalida.to_csv('salida.csv', index=False)